### ISSUE TITLE
Compilation error on Windows x64 on iojs 2.4.0

### ISSUE THREAD

**Issue by mafintosh** [Level/leveldown#207]
When trying to compile leveldown on Windows 7 x64 using iojs 2.4.0 I get the below errors

(Using iojs 1.8.1 it works fine)

```
> node-gyp rebuild
  leveldb.vcxproj -> c:\Users\prebuild\leveldown\build\Release\\leveldb.lib
  snappy.vcxproj -> c:\Users\prebuild\leveldown\build\Release\\snappy.lib
  batch.cc
c:\Users\prebuild\.node-gyp\2.4.0\deps\v8\include\v8.h(3949): error C2332: 'enum' : missing tag name [c:\Users\prebuild\leveldown\build\leveldown.vcxproj]
c:\Users\prebuild\.node-gyp\2.4.0\deps\v8\include\v8.h(3949): error C2236: unexpected 'class' 'v8::PropertyHandlerFlags'. Did you forget a ';'? [c:\Users\prebuild\leveldown\build\leveldown.vcxproj]
c:\Users\prebuild\.node-gyp\2.4.0\deps\v8\include\v8.h(3949): error C3381: 'v8::PropertyHandlerFlags' : assembly access specifiers are only available in code compiled with a /clr option [c:\Users\prebuild\leveldown\build\leveldown.vcxproj]
c:\Users\prebuild\.node-gyp\2.4.0\deps\v8\include\v8.h(3949): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int [c:\Users\prebuild\leveldown\build\leveldown.vcxproj]
c:\Users\prebuild\.node-gyp\2.4.0\deps\v8\include\v8.h(3949): error C2864: 'v8::PropertyHandlerFlags::kNone' : only static const integral data members can be initialized within a class [c:\Users\prebuild\leveldown\build\leveldown.vcxproj]
c:\Users\prebuild\.node-gyp\2.4.0\deps\v8\include\v8.h(3949): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int [c:\Users\prebuild\leveldown\build\leveldown.vcxproj]
c:\Users\prebuild\.node-gyp\2.4.0\deps\v8\include\v8.h(3949): error C2864: 'v8::PropertyHandlerFlags::kAllCanRead' : only static const integral data members can be initialized within a clgyp ERR! build error 
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (c:\Users\prebuild\AppData\Roaming\npm\node_modules\node-gyp\lib\build.js:269:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "c:\\Program Files\\iojs\\node.exe" "c:\\Users\\prebuild\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd c:\Users\prebuild\leveldown
gyp ERR! node -v v2.4.0
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
node-gyp\2.4.0\deps\v8\include\v8.h(3949) : see declaration of 'v8::PropertyHandlerFlags'
c:\Users\prebuild\.node-gyp\2.4.0\deps\v8\include\v8.h(3981): error C2039: 'kNone' : is not a member of 'v8::PropertyHandlerFlags' [c:\Users\prebuild\leveldown\build\leveldown.vcxproj]
          c:\Users\prebuild\.node-gyp\2.4.0\deps\v8\include\v8.h(3949) : see declaration of 'v8::PropertyHandlerFlags'
c:\Users\prebuild\.node-gyp\2.4.0\deps\v8\include\v8.h(3981): error C2039: 'kNone' : is not a member of 'v8::PropertyHandlerFlags' [c:\Users\prebuild\leveldown\build\leveldown.vcxproj]
          c:\Users\prebuild\.node-gyp\2.4.0\deps\v8\include\v8.h(3949) : see declaration of 'v8::PropertyHandlerFlags'
c:\Users\prebuild\.node-gyp\2.4.0\deps\v8\include\v8.h(3981): error C2065: 'kNone' : undeclared identifier [c:\Users\prebuild\leveldown\build\leveldown.vcxproj]
  batch_async.cc
c:\Users\prebuild\.node-gyp\2.4.0\deps\v8\include\v8.h(3949): error C2332: 'enum' : missing tag name [c:\Users\prebuild\leveldown\build\leveldown.vcxproj]
c:\Users\prebuild\.node-gyp\2.4.0\deps\v8\include\v8.h(3949): error C2236: unexpected 'class' 'v8::PropertyHandlerFlags'. Did you forget a ';'? [c:\Users\prebuild\leveldown\build\leveldown.vcxproj]
c:\Users\prebuild\.node-gyp\2.4.0\deps\v8\include\v8.h(3949): error C3381: 'v8::PropertyHandlerFlags' : assembly access specifiers are only available in code compiled with a /clr option [c:\Users\prebuild\leveldown\build\leveldown.vcxproj]
c:\Users\prebuild\.node-gyp\2.4.0\deps\v8\include\v8.h(3949): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int [c:\Users\prebuild\leveldown\build\leveldown.vcxproj]
c:\Users\prebuild\.node-gyp\2.4.0\deps\v8\include\v8.h(3949): error C2864: 'v8::PropertyHandlerFlags::kNone' : only static const integral data members can be initialized within a class [c:\Users\prebuild\leveldown\build\leveldown.vcxproj]
c:\Users\prebuild\.node-gyp\2.4.0\deps\v8\include\v8.h(3949): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int [c:\Users\prebuild\leveldown\build\leveldown.vcxproj]
c:\Users\prebuild\.node-gyp\2.4.0\deps\v8\include\v8.h(3949): error C2864: 'v8::PropertyHandlerFlags::kAllCanRead' : only static const integral data members can be initialized within a class [c:\Users\prebuild\leveldown\build\leveldown.vcxproj]
c:\Users\prebuild\.node-gyp\2.4.0\deps\v8\include\v8.h(3949): error C2143: syntax error : missing ';' before '}' [c:\Users\prebuild\leveldown\build\leveldown.vcxproj]
c:\Users\prebuild\.node-gyp\2.4.0\deps\v8\include\v8.h(3953): error C2039: 'kNone' : is not a member of 'v8::PropertyHandlerFlags' [c:\Users\prebuild\leveldown\build\leveldown.vcxproj]
          c:\Users\prebuild\.node-gyp\2.4.0\deps\v8\include\v8.h(3949) : see declaration of 'v8::PropertyHandlerFlags'
c:\Users\prebuild\.node-gyp\2.4.0\deps\v8\include\v8.h(3953): error C2039: 'kNone' : is not a member of 'v8::PropertyHandlerFlags' [c:\Users\prebuild\leveldown\build\leveldown.vcxproj]
          c:\Users\prebuild\.node-gyp\2.4.0\deps\v8\include\v8.h(3949) : see declaration of 'v8::PropertyHandlerFlags'
c:\Users\prebuild\.node-gyp\2.4.0\deps\v8\include\v8.h(3981): error C2039: 'kNone' : is not a member of 'v8::PropertyHandlerFlags' [c:\Users\prebuild\leveldown\build\leveldown.vcxproj]
          c:\Users\prebuild\.node-gyp\2.4.0\deps\v8\include\v8.h(3949) : see declaration of 'v8::PropertyHandlerFlags'
c:\Users\prebuild\.node-gyp\2.4.0\deps\v8\include\v8.h(3981): error C2039: 'kNone' : is not a member of 'v8::PropertyHandlerFlags' [c:\Users\prebuild\leveldown\build\leveldown.vcxproj]
          c:\Users\prebuild\.node-gyp\2.4.0\deps\v8\include\v8.h(3949) : see declaration of 'v8::PropertyHandlerFlags'
c:\Users\prebuild\.node-gyp\2.4.0\deps\v8\include\v8.h(3981): error C2065: 'kNone' : undeclared identifier [c:\Users\prebuild\leveldown\build\leveldown.vcxproj]
  database.cc
c:\Users\prebuild\.node-gyp\2.4.0\deps\v8\include\v8.h(3949): error C2332: 'enum' : missing tag name [c:\Users\prebuild\leveldown\build\leveldown.vcxproj]
c:\Users\prebuild\.node-gyp\2.4.0\deps\v8\include\v8.h(3949): error C2236: unexpected 'class' 'v8::PropertyHandlerFlags'. Did you forget a ';'? [c:\Users\prebuild\leveldown\build\leveldown.vcxproj]
c:\Users\prebuild\.node-gyp\2.4.0\deps\v8\include\v8.h(3949): error C3381: 'v8::PropertyHandlerFlags' : assembly access specifiers are only available in code compiled with a /clr option [c:\Users\prebuild\leveldown\build\leveldown.vcxproj]
c:\Users\prebuild\.node-gyp\2.4.0\deps\v8\include\v8.h(3949): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int [c:\Users\prebuild\leveldown\build\leveldown.vcxproj]
c:\Users\prebuild\.node-gyp\2.4.0\deps\v8\include\v8.h(3949): error C2864: 'v8::PropertyHandlerFlags::kNone' : only static const integral data members can be initialized within a class [c:\Users\prebuild\leveldown\build\leveldown.vcxproj]
c:\Users\prebuild\.node-gyp\2.4.0\deps\v8\include\v8.h(3949): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int [c:\Users\prebuild\leveldown\build\leveldown.vcxproj]
c:\Users\prebuild\.node-gyp\2.4.0\deps\v8\include\v8.h(3949): error C2864: 'v8::PropertyHandlerFlags::kAllCanRead' : only static const integral data members can be initialized within a class [c:\Users\prebuild\leveldown\build\leveldown.vcxproj]
c:\Users\prebuild\.node-gyp\2.4.0\deps\v8\include\v8.h(3949): error C2143: syntax error : missing ';' before '}' [c:\Users\prebuild\leveldown\build\leveldown.vcxproj]
c:\Users\prebuild\.node-gyp\2.4.0\deps\v8\include\v8.h(3953): error C2039: 'kNone' : is not a member of 'v8::PropertyHandlerFlags' [c:\Users\prebuild\leveldown\build\leveldown.vcxproj]
          c:\Users\prebuild\.node-gyp\2.4.0\deps\v8\include\v8.h(3949) : see declaration of 'v8::PropertyHandlerFlags'
c:\Users\prebuild\.node-gyp\2.4.0\deps\v8\include\v8.h(3953): error C2039: 'kNone' : is not a member of 'v8::PropertyHandlerFlags' [c:\Users\prebuild\leveldown\build\leveldown.vcxproj]
          c:\Users\prebuild\.node-gyp\2.4.0\deps\v8\include\v8.h(3949) : see declaration of 'v8::PropertyHandlerFlags'
c:\Users\prebuild\.node-gyp\2.4.0\deps\v8\include\v8.h(3981): error C2039: 'kNone' : is not a member of 'v8::PropertyHandlerFlags' [c:\Users\prebuild\leveldown\build\leveldown.vcxproj]
          c:\Users\prebuild\.node-gyp\2.4.0\deps\v8\include\v8.h(3949) : see declaration of 'v8::PropertyHandlerFlags'
c:\Users\prebuild\.node-gyp\2.4.0\deps\v8\include\v8.h(3981): error C2039: 'kNone' : is not a member of 'v8::PropertyHandlerFlags' [c:\Users\prebuild\leveldown\build\leveldown.vcxproj]
          c:\Users\prebuild\.node-gyp\2.4.0\deps\v8\include\v8.h(3949) : see declaration of 'v8::PropertyHandlerFlags'
c:\Users\prebuild\.node-gyp\2.4.0\deps\v8\include\v8.h(3981): error C2065: 'kNone' : undeclared identifier [c:\Users\prebuild\leveldown\build\leveldown.vcxproj]
  database_async.cc
c:\Users\prebuild\.node-gyp\2.4.0\deps\v8\include\v8.h(3949): error C2332: 'enum' : missing tag name [c:\Users\prebuild\leveldown\build\leveldown.vcxproj]
c:\Users\prebuild\.node-gyp\2.4.0\deps\v8\include\v8.h(3949): error C2236: unexpected 'class' 'v8::PropertyHandlerFlags'. Did you forget a ';'? [c:\Users\prebuild\leveldown\build\leveldown.vcxproj]
c:\Users\prebuild\.node-gyp\2.4.0\deps\v8\include\v8.h(3949): error C3381: 'v8::PropertyHandlerFlags' : assembly access specifiers are only available in code compiled with a /clr option [c:\Users\prebuild\leveldown\build\leveldown.vcxproj]
c:\Users\prebuild\.node-gyp\2.4.0\deps\v8\include\v8.h(3949): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int [c:\Users\prebuild\leveldown\build\leveldown.vcxproj]
c:\Users\prebuild\.node-gyp\2.4.0\deps\v8\include\v8.h(3949): error C2864: 'v8::PropertyHandlerFlags::kNone' : only static const integral data members can be initialized within a class [c:\Users\prebuild\leveldown\build\leveldown.vcxproj]
c:\Users\prebuild\.node-gyp\2.4.0\deps\v8\include\v8.h(3949): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int [c:\Users\prebuild\leveldown\build\leveldown.vcxproj]
c:\Users\prebuild\.node-gyp\2.4.0\deps\v8\include\v8.h(3949): error C2864: 'v8::PropertyHandlerFlags::kAllCanRead' : only static const integral data members can be initialized within a class [c:\Users\prebuild\leveldown\build\leveldown.vcxproj]
c:\Users\prebuild\.node-gyp\2.4.0\deps\v8\include\v8.h(3949): error C2143: syntax error : missing ';' before '}' [c:\Users\prebuild\leveldown\build\leveldown.vcxproj]
c:\Users\prebuild\.node-gyp\2.4.0\deps\v8\include\v8.h(3953): error C2039: 'kNone' : is not a member of 'v8::PropertyHandlerFlags' [c:\Users\prebuild\leveldown\build\leveldown.vcxproj]
          c:\Users\prebuild\.node-gyp\2.4.0\deps\v8\include\v8.h(3949) : see declaration of 'v8::PropertyHandlerFlags'
c:\Users\prebuild\.node-gyp\2.4.0\deps\v8\include\v8.h(3953): error C2039: 'kNone' : is not a member of 'v8::PropertyHandlerFlags' [c:\Users\prebuild\leveldown\build\leveldown.vcxproj]
          c:\Users\prebuild\.node-gyp\2.4.0\deps\v8\include\v8.h(3949) : see declaration of 'v8::PropertyHandlerFlags'
c:\Users\prebuild\.node-gyp\2.4.0\deps\v8\include\v8.h(3981): error C2039: 'kNone' : is not a member of 'v8::PropertyHandlerFlags' [c:\Users\prebuild\leveldown\build\leveldown.vcxproj]
          c:\Users\prebuild\.node-gyp\2.4.0\deps\v8\include\v8.h(3949) : see declaration of 'v8::PropertyHandlerFlags'
c:\Users\prebuild\.node-gyp\2.4.0\deps\v8\include\v8.h(3981): error C2039: 'kNone' : is not a member of 'v8::PropertyHandlerFlags' [c:\Users\prebuild\leveldown\build\leveldown.vcxproj]
          c:\Users\prebuild\.node-gyp\2.4.0\deps\v8\include\v8.h(3949) : see declaration of 'v8::PropertyHandlerFlags'
c:\Users\prebuild\.node-gyp\2.4.0\deps\v8\include\v8.h(3981): error C2065: 'kNone' : undeclared identifier [c:\Users\prebuild\leveldown\build\leveldown.vcxproj]
  iterator.cc
c:\Users\prebuild\.node-gyp\2.4.0\deps\v8\include\v8.h(3949): error C2332: 'enum' : missing tag name [c:\Users\prebuild\leveldown\build\leveldown.vcxproj]
c:\Users\prebuild\.node-gyp\2.4.0\deps\v8\include\v8.h(3949): error C2236: unexpected 'class' 'v8::PropertyHandlerFlags'. Did you forget a ';'? [c:\Users\prebuild\leveldown\build\leveldown.vcxproj]
c:\Users\prebuild\.node-gyp\2.4.0\deps\v8\include\v8.h(3949): error C3381: 'v8::PropertyHandlerFlags' : assembly access specifiers are only available in code compiled with a /clr option [c:\Users\prebuild\leveldown\build\leveldown.vcxproj]
c:\Users\prebuild\.node-gyp\2.4.0\deps\v8\include\v8.h(3949): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int [c:\Users\prebuild\leveldown\build\leveldown.vcxproj]
c:\Users\prebuild\.node-gyp\2.4.0\deps\v8\include\v8.h(3949): error C2864: 'v8::PropertyHandlerFlags::kNone' : only static const integral data members can be initialized within a class [c:\Users\prebuild\leveldown\build\leveldown.vcxproj]
c:\Users\prebuild\.node-gyp\2.4.0\deps\v8\include\v8.h(3949): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int [c:\Users\prebuild\leveldown\build\leveldown.vcxproj]
c:\Users\prebuild\.node-gyp\2.4.0\deps\v8\include\v8.h(3949): error C2864: 'v8::PropertyHandlerFlags::kAllCanRead' : only static const integral data members can be initialized within a class [c:\Users\prebuild\leveldown\build\leveldown.vcxproj]
c:\Users\prebuild\.node-gyp\2.4.0\deps\v8\include\v8.h(3949): error C2143: syntax error : missing ';' before '}' [c:\Users\prebuild\leveldown\build\leveldown.vcxproj]
c:\Users\prebuild\.node-gyp\2.4.0\deps\v8\include\v8.h(3953): error C2039: 'kNone' : is not a member of 'v8::PropertyHandlerFlags' [c:\Users\prebuild\leveldown\build\leveldown.vcxproj]
          c:\Users\prebuild\.node-gyp\2.4.0\deps\v8\include\v8.h(3949) : see declaration of 'v8::PropertyHandlerFlags'
c:\Users\prebuild\.node-gyp\2.4.0\deps\v8\include\v8.h(3953): error C2039: 'kNone' : is not a member of 'v8::PropertyHandlerFlags' [c:\Users\prebuild\leveldown\build\leveldown.vcxproj]
          c:\Users\prebuild\.node-gyp\2.4.0\deps\v8\include\v8.h(3949) : see declaration of 'v8::PropertyHandlerFlags'
c:\Users\prebuild\.node-gyp\2.4.0\deps\v8\include\v8.h(3981): error C2039: 'kNone' : is not a member of 'v8::PropertyHandlerFlags' [c:\Users\prebuild\leveldown\build\leveldown.vcxproj]
          c:\Users\prebuild\.node-gyp\2.4.0\deps\v8\include\v8.h(3949) : see declaration of 'v8::PropertyHandlerFlags'
c:\Users\prebuild\.node-gyp\2.4.0\deps\v8\include\v8.h(3981): error C2039: 'kNone' : is not a member of 'v8::PropertyHandlerFlags' [c:\Users\prebuild\leveldown\build\leveldown.vcxproj]
          c:\Users\prebuild\.node-gyp\2.4.0\deps\v8\include\v8.h(3949) : see declaration of 'v8::PropertyHandlerFlags'
c:\Users\prebuild\.node-gyp\2.4.0\deps\v8\include\v8.h(3981): error C2065: 'kNone' : undeclared identifier [c:\Users\prebuild\leveldown\build\leveldown.vcxproj]
  iterator_async.cc
c:\Users\prebuild\.node-gyp\2.4.0\deps\v8\include\v8.h(3949): error C2332: 'enum' : missing tag name [c:\Users\prebuild\leveldown\build\leveldown.vcxproj]
c:\Users\prebuild\.node-gyp\2.4.0\deps\v8\include\v8.h(3949): error C2236: unexpected 'class' 'v8::PropertyHandlerFlags'. Did you forget a ';'? [c:\Users\prebuild\leveldown\build\leveldown.vcxproj]
c:\Users\prebuild\.node-gyp\2.4.0\deps\v8\include\v8.h(3949): error C3381: 'v8::PropertyHandlerFlags' : assembly access specifiers are only available in code compiled with a /clr option [c:\Users\prebuild\leveldown\build\leveldown.vcxproj]
c:\Users\prebuild\.node-gyp\2.4.0\deps\v8\include\v8.h(3949): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int [c:\Users\prebuild\leveldown\build\leveldown.vcxproj]
c:\Users\prebuild\.node-gyp\2.4.0\deps\v8\include\v8.h(3949): error C2864: 'v8::PropertyHandlerFlags::kNone' : only static const integral data members can be initialized within a class [c:\Users\prebuild\leveldown\build\leveldown.vcxproj]
c:\Users\prebuild\.node-gyp\2.4.0\deps\v8\include\v8.h(3949): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int [c:\Users\prebuild\leveldown\build\leveldown.vcxproj]
c:\Users\prebuild\.node-gyp\2.4.0\deps\v8\include\v8.h(3949): error C2864: 'v8::PropertyHandlerFlags::kAllCanRead' : only static const integral data members can be initialized within a class [c:\Users\prebuild\leveldown\build\leveldown.vcxproj]
c:\Users\prebuild\.node-gyp\2.4.0\deps\v8\include\v8.h(3949): error C2143: syntax error : missing ';' before '}' [c:\Users\prebuild\leveldown\build\leveldown.vcxproj]
c:\Users\prebuild\.node-gyp\2.4.0\deps\v8\include\v8.h(3953): error C2039: 'kNone' : is not a member of 'v8::PropertyHandlerFlags' [c:\Users\prebuild\leveldown\build\leveldown.vcxproj]
          c:\Users\prebuild\.node-gyp\2.4.0\deps\v8\include\v8.h(3949) : see declaration of 'v8::PropertyHandlerFlags'
c:\Users\prebuild\.node-gyp\2.4.0\deps\v8\include\v8.h(3953): error C2039: 'kNone' : is not a member of 'v8::PropertyHandlerFlags' [c:\Users\prebuild\leveldown\build\leveldown.vcxproj]
          c:\Users\prebuild\.node-gyp\2.4.0\deps\v8\include\v8.h(3949) : see declaration of 'v8::PropertyHandlerFlags'
c:\Users\prebuild\.node-gyp\2.4.0\deps\v8\include\v8.h(3981): error C2039: 'kNone' : is not a member of 'v8::PropertyHandlerFlags' [c:\Users\prebuild\leveldown\build\leveldown.vcxproj]
          c:\Users\prebuild\.node-gyp\2.4.0\deps\v8\include\v8.h(3949) : see declaration of 'v8::PropertyHandlerFlags'
c:\Users\prebuild\.node-gyp\2.4.0\deps\v8\include\v8.h(3981): error C2039: 'kNone' : is not a member of 'v8::PropertyHandlerFlags' [c:\Users\prebuild\leveldown\build\leveldown.vcxproj]
          c:\Users\prebuild\.node-gyp\2.4.0\deps\v8\include\v8.h(3949) : see declaration of 'v8::PropertyHandlerFlags'
c:\Users\prebuild\.node-gyp\2.4.0\deps\v8\include\v8.h(3981): error C2065: 'kNone' : undeclared identifier [c:\Users\prebuild\leveldown\build\leveldown.vcxproj]
  leveldown.cc
c:\Users\prebuild\.node-gyp\2.4.0\deps\v8\include\v8.h(3949): error C2332: 'enum' : missing tag name [c:\Users\prebuild\leveldown\build\leveldown.vcxproj]
c:\Users\prebuild\.node-gyp\2.4.0\deps\v8\include\v8.h(3949): error C2236: unexpected 'class' 'v8::PropertyHandlerFlags'. Did you forget a ';'? [c:\Users\prebuild\leveldown\build\leveldown.vcxproj]
c:\Users\prebuild\.node-gyp\2.4.0\deps\v8\include\v8.h(3949): error C3381: 'v8::PropertyHandlerFlags' : assembly access specifiers are only available in code compiled with a /clr option [c:\Users\prebuild\leveldown\build\leveldown.vcxproj]
c:\Users\prebuild\.node-gyp\2.4.0\deps\v8\include\v8.h(3949): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int [c:\Users\prebuild\leveldown\build\leveldown.vcxproj]
c:\Users\prebuild\.node-gyp\2.4.0\deps\v8\include\v8.h(3949): error C2864: 'v8::PropertyHandlerFlags::kNone' : only static const integral data members can be initialized within a class [c:\Users\prebuild\leveldown\build\leveldown.vcxproj]
c:\Users\prebuild\.node-gyp\2.4.0\deps\v8\include\v8.h(3949): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int [c:\Users\prebuild\leveldown\build\leveldown.vcxproj]
c:\Users\prebuild\.node-gyp\2.4.0\deps\v8\include\v8.h(3949): error C2864: 'v8::PropertyHandlerFlags::kAllCanRead' : only static const integral data members can be initialized within a class [c:\Users\prebuild\leveldown\build\leveldown.vcxproj]
c:\Users\prebuild\.node-gyp\2.4.0\deps\v8\include\v8.h(3949): error C2143: syntax error : missing ';' before '}' [c:\Users\prebuild\leveldown\build\leveldown.vcxproj]
c:\Users\prebuild\.node-gyp\2.4.0\deps\v8\include\v8.h(3953): error C2039: 'kNone' : is not a member of 'v8::PropertyHandlerFlags' [c:\Users\prebuild\leveldown\build\leveldown.vcxproj]
          c:\Users\prebuild\.node-gyp\2.4.0\deps\v8\include\v8.h(3949) : see declaration of 'v8::PropertyHandlerFlags'
c:\Users\prebuild\.node-gyp\2.4.0\deps\v8\include\v8.h(3953): error C2039: 'kNone' : is not a member of 'v8::PropertyHandlerFlags' [c:\Users\prebuild\leveldown\build\leveldown.vcxproj]
          c:\Users\prebuild\.node-gyp\2.4.0\deps\v8\include\v8.h(3949) : see declaration of 'v8::PropertyHandlerFlags'
c:\Users\prebuild\.node-gyp\2.4.0\deps\v8\include\v8.h(3981): error C2039: 'kNone' : is not a member of 'v8::PropertyHandlerFlags' [c:\Users\prebuild\leveldown\build\leveldown.vcxproj]
          c:\Users\prebuild\.node-gyp\2.4.0\deps\v8\include\v8.h(3949) : see declaration of 'v8::PropertyHandlerFlags'
c:\Users\prebuild\.node-gyp\2.4.0\deps\v8\include\v8.h(3981): error C2039: 'kNone' : is not a member of 'v8::PropertyHandlerFlags' [c:\Users\prebuild\leveldown\build\leveldown.vcxproj]
          c:\Users\prebuild\.node-gyp\2.4.0\deps\v8\include\v8.h(3949) : see declaration of 'v8::PropertyHandlerFlags'
c:\Users\prebuild\.node-gyp\2.4.0\deps\v8\include\v8.h(3981): error C2065: 'kNone' : undeclared identifier [c:\Users\prebuild\leveldown\build\leveldown.vcxproj]
  leveldown_async.cc
c:\Users\prebuild\.node-gyp\2.4.0\deps\v8\include\v8.h(3949): error C2332: 'enum' : missing tag name [c:\Users\prebuild\leveldown\build\leveldown.vcxproj]
c:\Users\prebuild\.node-gyp\2.4.0\deps\v8\include\v8.h(3949): error C2236: unexpected 'class' 'v8::PropertyHandlerFlags'. Did you forget a ';'? [c:\Users\prebuild\leveldown\build\leveldown.vcxproj]
c:\Users\prebuild\.node-gyp\2.4.0\deps\v8\include\v8.h(3949): error C3381: 'v8::PropertyHandlerFlags' : assembly access specifiers are only available in code compiled with a /clr option [c:\Users\prebuild\leveldown\build\leveldown.vcxproj]
c:\Users\prebuild\.node-gyp\2.4.0\deps\v8\include\v8.h(3949): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int [c:\Users\prebuild\leveldown\build\leveldown.vcxproj]
c:\Users\prebuild\.node-gyp\2.4.0\deps\v8\include\v8.h(3949): error C2864: 'v8::PropertyHandlerFlags::kNone' : only static const integral data members can be initialized within a class [c:\Users\prebuild\leveldown\build\leveldown.vcxproj]
c:\Users\prebuild\.node-gyp\2.4.0\deps\v8\include\v8.h(3949): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int [c:\Users\prebuild\leveldown\build\leveldown.vcxproj]
c:\Users\prebuild\.node-gyp\2.4.0\deps\v8\include\v8.h(3949): error C2864: 'v8::PropertyHandlerFlags::kAllCanRead' : only static const integral data members can be initialized within a class [c:\Users\prebuild\leveldown\build\leveldown.vcxproj]
c:\Users\prebuild\.node-gyp\2.4.0\deps\v8\include\v8.h(3949): error C2143: syntax error : missing ';' before '}' [c:\Users\prebuild\leveldown\build\leveldown.vcxproj]
c:\Users\prebuild\.node-gyp\2.4.0\deps\v8\include\v8.h(3953): error C2039: 'kNone' : is not a member of 'v8::PropertyHandlerFlags' [c:\Users\prebuild\leveldown\build\leveldown.vcxproj]
          c:\Users\prebuild\.node-gyp\2.4.0\deps\v8\include\v8.h(3949) : see declaration of 'v8::PropertyHandlerFlags'
c:\Users\prebuild\.node-gyp\2.4.0\deps\v8\include\v8.h(3953): error C2039: 'kNone' : is not a member of 'v8::PropertyHandlerFlags' [c:\Users\prebuild\leveldown\build\leveldown.vcxproj]
          c:\Users\prebuild\.node-gyp\2.4.0\deps\v8\include\v8.h(3949) : see declaration of 'v8::PropertyHandlerFlags'
c:\Users\prebuild\.node-gyp\2.4.0\deps\v8\include\v8.h(3981): error C2039: 'kNone' : is not a member of 'v8::PropertyHandlerFlags' [c:\Users\prebuild\leveldown\build\leveldown.vcxproj]
          c:\Users\prebuild\.node-gyp\2.4.0\deps\v8\include\v8.h(3949) : see declaration of 'v8::PropertyHandlerFlags'
c:\Users\prebuild\.node-gyp\2.4.0\deps\v8\include\v8.h(3981): error C2039: 'kNone' : is not a member of 'v8::PropertyHandlerFlags' [c:\Users\prebuild\leveldown\build\leveldown.vcxproj]
          c:\Users\prebuild\.node-gyp\2.4.0\deps\v8\include\v8.h(3949) : see declaration of 'v8::PropertyHandlerFlags'
c:\Users\prebuild\.node-gyp\2.4.0\deps\v8\include\v8.h(3981): error C2065: 'kNone' : undeclared identifier [c:\Users\prebuild\leveldown\build\leveldown.vcxproj]
```

**Comment by No9** [comment]
So just to make sure I am testing the right thing as ```node-gyp rebuild``` is bauking on my config
(404 trying to get v2.5.0 is a yak I don't want to shave)
Using **iojs 2.5.0** on **master**
```bash
$ git clone https://github.com/Level/leveldown.git
$ cd leveldown
$ npm install
```
This works 

```bash
$ npm test

test repair non-existant directory returns error
  not ok 736 error on callback
    ---
      operator: ok
      expected: true
      actual:   false
    ...
# test repair() compacts
  ok 737 no error from open()
  ok 738 no error from batch()
  ok 739 no error
  ok 740 directory contains log file(s)
  ok 741 directory does not contain ldb file(s)
  ok 742 directory does not contain log file(s)
  test repair() compactsins ldb file(s)

# tests 743
tests 743
# pass  742
pass  742
fail  1
```
So apart from the `repair non-existant directory returns error` this looks good to me. 

Or should I be testing something else specifically

**Comment by mafintosh** [comment]
@No9 is this on Windows 7 64bit?

**Comment by No9** [comment]
@mafintosh yup N.B. IOJS 2.5.0

**Comment by mafintosh** [comment]
@No9 just tried with 2.5.0 and its still failing, which version of visual studio do you use?

**Comment by ralphtheninja** [comment]
@mafintosh I suspect this is related to your compiler not having c++11 support (strongly typed enums) http://www.cprogramming.com/c++11/c++11-nullptr-strongly-typed-enum-class.html

**Comment by No9** [comment]
@mafintosh  I am on VS 2013 upgraded from 2010 though 
with a winsdk 7.1 thrown in for goodluck
If I get time I would like to take https://msdn.microsoft.com/en-us/windows/desktop/bg162891.aspx for a drive to see how straight forward this can be made.
But there are always other things to do :/

**Comment by mafintosh** [comment]
Dang. Guess I'll have to try upgrading the VS on the prebuild vm :/ @No9 How do I upgrade from VS2010 to VS2013? And did you need to do other stuff to get compilation to work?

**Comment by No9** [comment]
I put it on top of the 2010 install using the normal install.msi
I didn't uninstall 2010.

You can have them on the same machine and get the goodness of both worlds :) 

You will have to use the --msvs-version=2013 flag and not be afraid of debugging with procmon if you hit some issues. 
https://technet.microsoft.com/en-us/library/bb896645.aspx 
I seem to recall I had some registry settings that didn't roll over as expected. 
I can't find my notes but I remember searching for the key errors given by procmon and got some answers.
Hope this helps

**Comment by mafintosh** [comment]
@No9 do i have to use the `--msvs-version=2013` flag when compiling with node-gyp? (i am a windows noob :))

**Comment by No9** [comment]
If you have 2013 installed and it's default which it will be if you install over 2010 then yes
There is a global environment you can set I'll post it when I get to big screen

**Comment by mafintosh** [comment]
Awesome - thanks

**Comment by No9** [comment]
Click Start 
And search for `systempropertiesadvanced`
Click to run 
Click the `Environment Variables` at the bottom of the form 
In the system variables pane add a new one with 
name : `GYP_MSVS_VERSION` 
value : `2013`
Save all 
You will have to restart any consoles to pick up the change 
Validate in an new console with 
```
> echo %GYP_MSVS_VERSION%
2013
```

no worries about the noob bit - I'm happy to help out. 
I am currently in the middle of "borrowing" all your level-filesystem test for chrome-fs :) 
https://github.com/No9/chrome-fs/tree/master/test/dat-test

**Comment by rvagg** [comment]
I'd remove 2010 completely, no reason to have both, even for compiling for Node 0.10. Go to "Add and Remove Programs" in the Control Panel and purge all of the cruft it installs, including all of the SQL Server garbage.

If you just have 2013 installed then you shouldn't have to worry about the `--msvs-version=2013` stuff.

If you need more hints, https://github.com/nodejs/build/tree/master/setup/windows has some info, just follow the instructions there for MSVS, Python and Git and you should have everything you need for Windows dev.

**Comment by No9** [comment]
@rvagg So @mafintosh went for a straight 2013 SP 5 setup and ran into this 
https://github.com/TooTallNate/node-gyp/issues/479 
'ammintrin.h' (Really want to call this the 'amirite' bug) 
This was resolved in 2010 sp1 but looks to have been reintroduced with some later security updates and impacts a 2013 straight install on win7

I am not seeing this issue on win7 so concluded that it was due to my dual install. 
But happy to be corrected.. 

Agreed that a single install shouldn't need to worry about --msvs-version=2013

TBH I feel we need https://github.com/nodejs/build/tree/master/setup/windows but validated for Desktop versions of windows 
Or maybe a link at the top of that setup that points to a 2008 ISO?

**Comment by No9** [comment]
k so I am going to get this 2008 and take this for a spin tomorrow 
http://www.microsoft.com/en-ie/download/details.aspx?id=11093 
Thanks for the node windows install I hadn't seen that before.

**Comment by mafintosh** [comment]
Getting VS2013 to work on 32bit was easy. All the pain and suffering started on 64 bit

**Comment by darsain** [comment]
I'm running:

- Win 8.1
- io.js@3.0.0 x86 + npm@2.13.3
- Visual Studio Express 2013 with Update 5 for Windows Desktop
- Windows 7 64-bit SDK

and I'm getting this: https://gist.github.com/anonymous/3fa229dbc0b1b0352786

I've tried downgrading io.js to `2.5.0`, `2.4.0`, `2.3.4` and on all of these versions I'm instead getting:

```
> leveldown@1.4.0 install D:\node\test\node_modules\leveldown
> prebuild --download

prebuild WARN install Module did not self-register.
prebuild ERR! build EPERM: operation not permitted, unlink 'D:\node\test\node_mo
dules\leveldown\build\Release\leveldown.node'
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files (x86)\\iojs\\node.exe" "C:\\Program Files (x86)
\\iojs\\node_modules\\npm\\bin\\npm-cli.js" "install" "leveldown"
npm ERR! node v2.4.0
npm ERR! npm  v2.13.0
npm ERR! code ELIFECYCLE
```

Nothing is set as read only. The whole directory is even successfully cleaned up afterwards.

Also tried latest node `0.12.7`, where it installed correctly. It seemed it downloaded prebuild binary as there was no indication of compilation in stdout. Would it be that much of a problem providing prebuild binaries also for iojs like other modules do?

But in the meantime, any ideas what to do? Literally spent the whole day on this, and I'm out of ideas.

**Comment by ralphtheninja** [comment]
@darsain We are providing binaries for iojs, but we haven't built for iojs 3.0.0 yet (new ABI version). So this explains why you had to switch to another iojs version.

Now, the reason why it still doesn't work for the other versions is the real issue here. So to me it seems `prebuild` fails to `require()` the leveldown binary (e.g. `WARN install Module did not self-register`), which tells me somehow you are getting the wrong binary for your system. This should fall back to a compile step which also seems to fail.

It would be useful if you could do `npm i leveldown --verbose` and post that output to a gist or something and share that.

@mafintosh Any ideas?

**Comment by darsain** [comment]
@ralphtheninja https://gist.github.com/anonymous/f2c8cf620a58d43f8eea

**Comment by ralphtheninja** [comment]
@darsain I believe that `node-gyp` fails with the clean step:

```
prebuild verb clean removing "build" directory
prebuild ERR! build EPERM: operation not permitted, unlink 'D:\node\test\node_modules\leveldown\build\Release\leveldown.node'
```

So there is some kind of odd problem with permissions on your windows machine. Not sure yet how to get around it.

**Comment by darsain** [comment]
I tried applying and triple checking the permissions, and also installing into different newly created folders, different HDDs, I even made a new partition, just to rule the permissions out completely :) Still the same error.

So it doesn't seem like it's in permissions, which is also supported by isaacs in one of the similar issues to this one:

> "EPERM" isn't "permission denied" exactly (that's EACCES.) EPERM is "operation not permitted". There are some things that even root isn't allowed to do, like write to a read-only file system, or cd into a file, or unlink a dir, etc.

... or when something else is still using the file, and not releasing the file descriptor.

Maybe related would be https://github.com/joyent/node/issues/3051 issue.

**Comment by jkrot** [comment]
I have this same issue you can see more info in https://github.com/pouchdb/pouchdb/issues/4173  using VS 2012 Premium which shouldn't have this issue like VS 2010.

**Comment by rvagg** [comment]
does VS 2012 actually work for compiling against io.js? I thought it was 2013 or higher given the C++11 features in V8.

**Comment by No9** [comment]
Also something weird in that final screen shot as it says `node -v 0.12.7` and it's an `ETIMEOUT`
![Screenshot](https://cloud.githubusercontent.com/assets/124587/9333262/938a4870-458e-11e5-8a15-76e3fcca0277.PNG)
Seems to be a lower level setup problem mixed with an connectivity issue?

**Comment by jkrot** [comment]
Thats just a timeout with express because another dependency  failed.

**Comment by ralphtheninja** [comment]
@mafintosh [This comment](https://github.com/nodejs/node-gyp/issues/629#issuecomment-138276692) might be useful for making x64 work with windows

**Comment by darsain** [comment]
So I've finally had a chance to test the installation of prebuild binaries on Win 8 on a different machine (with completely different HW) to completely rule out the possibility that the report above is something with my environment, and got the exact same error:

```
D:\test>npm install leveldown
|
> leveldown@1.4.1 install D:\test\node_modules\leveldown
> prebuild --download

prebuild WARN install Module did not self-register.
prebuild ERR! build EPERM: operation not permitted, unlink 'D:\test\node_modules\leveldown\build\Release\leveldown.node'
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files (x86)\\iojs\\node.exe" "C:\\Program Files (x86)\\iojs\\node_modules\\npm\\bin\\npm-cli.js" "install" "leveldown"
npm ERR! node v2.5.0
npm ERR! npm  v2.13.2
npm ERR! code ELIFECYCLE

npm ERR! leveldown@1.4.1 install: `prebuild --download`
npm ERR! Exit status 2
```

Environment:
- Win 8 x64
- iojs 2.0.0-2.5.0 x86 *(x64 versions don't download prebuild binaries but try to build locally, which fails from different reasons)*

But as stated above, it works on node `0.12`. I have some details as to what might be the root of this issue in my last comment here, but apart of that I'm clueless.

**Comment by jkrot** [comment]
I was using node 0.12.7 Windows & x64 with VS 2013 Premium installed when I got my above error.  I will try again on my home machine which has windows 10 on it but still been frustrating.

**Comment by No9** [comment]
Hi @jkrot prebuild should now work for 0.12.7 x64 I put it up a couple of days ago.
https://github.com/Level/leveldown/issues/214 
So you shouldn't be building at all if you are installing pouch.
Or is this a different use case?

**Comment by jkrot** [comment]
Pouch is fine now i was still trying to build leveldown with different
versions of vs to see what would work.

**Comment by No9** [comment]
Hi @jkrot 
If we are still talking about the `EPERM` I haven't been able to replicate this nor I have I seen first hand in the wild. 

As it's an issue on a number of different projects as well as leveldown would you mind installing proc mon 
https://technet.microsoft.com/en-us/library/bb896645.aspx 
And run it while you are doing a build. 
After you can filter the trace with the string `leveldown.node` and we can see the processes that are trying to access the file.
At the very least this will rule out anti-virus. 
Hope you can help

**Comment by darsain** [comment]
So this: https://gist.github.com/anonymous/a8754ac9ecc8c38fe02b

is the procmon log of what happens with `leveldown.node` file during this error:

```
> leveldown@1.4.1 install D:\node\test\node_modules\leveldown
> prebuild --download

prebuild WARN install Module did not self-register.
prebuild ERR! build EPERM: operation not permitted, unlink 'D:\node\test\node_modules\leveldown\build\Release\leveldown.node'
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files (x86)\\iojs\\node.exe" "C:\\Users\\Darsain\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "leveldown"
npm ERR! node v2.5.0
npm ERR! npm  v3.2.2
npm ERR! code ELIFECYCLE
```

**Comment by ralphtheninja** [comment]
I'd really love it if we could pin this down and kill it with fire once and for all.
